#-------------------------------
# Site Settings
title: Priam
description: Priam is a minimal portfolio theme for Jekyll.
color_scheme: auto # You have the option to choose between three modes: auto, light, and dark. The default mode is set to auto, which means that the color scheme will automatically adapt based on your operating system settings. This way, you can enjoy a personalized experience without having to manually switch between light and dark modes.


#-------------------------------
# Global Cover
global_cover:
  enable: true
  homepage_image: "/images/meadowsPark.jpg" # This line allows you to add a beautiful image at the top of your site, creating an eye-catching visual element that enhances the overall appearance and appeal.


#-------------------------------
# Breadcrumbs
breadcrumbs:
  enable: true # This line of code enables you to easily incorporate breadcrumbs into your website. By setting the "enable" parameter to "true", breadcrumbs will be enabled on your website, allowing users to easily track their navigation and find relevant information. Conversely, setting the parameter to "false" will disable the display of breadcrumbs, removing this navigation feature from your website.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'üè† Home'
      url: '/'
    - title: 'üöÄ Projects'
      url: '/projects/'
    - title: 'üé¨ Videos'
      url: '/videos/'
    - title: 'üë®üèª‚Äçüíª About'
      url: '/about/'
    - title: 'üì∑ Gallery'
      url: '/gallery/'
    - title: '‚úçÔ∏è Blog'
      url: '/blog/'
    - title: 'üìî Elements'
      url: '/elements/'


#-------------------------------
# Author Settings
author:
  author_name: Addison Lin
  author_role: CS Undergraduate at University of Oklahoma
  author_bio: |
    Hello friends, welcome to my personal corner of the internet. I enjoy building with code, playing on the tennis court, traveling the world, and discovering the best food wherever I go.

    Zhou Xun (Âë®ËøÖ) once said:
    "Time is incredibly precious ‚Äî don‚Äôt waste it on things that don‚Äôt matter. Live in the present, and occasionally look ahead. The second that just passed is already eternity."

    Whenever I witness something beautiful happening, I wish time could stand still.
  author_avatar: '/images/front_head_shot.jpg'

  cta_button_text: Get In Touch
  cta_button_link: '/contact/'


#-------------------------------
# Projects Settings
projects_settings:
  enable: true
  projects_title: Portfolio
  projects_description:


#-------------------------------
# Testimonials Settings
testimonials:
  enable: false
  testimonials_title: Testimonials
  testimonials_description:

testimonial_items:
  - name: "Albert Flores"
    image: "/images/client-1.jpg"
    designation: "Data Scientist"
    content : "The incredible attention to detail displayed by this team is commendable. Every aspect of our project, no matter how small, was handled with precision and care. The result is a product that reflects their commitment to excellence."

  - name: "Wade Warren"
    image: "/images/client-2.jpg"
    designation: "DevOps Engineer"
    content : "Working with this creative powerhouse was an enlightening experience. Their brilliance in design thinking and creative solutions brought our project to life in ways we hadn't imagined. The team's passion for innovation is truly infectious."

  - name: "Jenny Wilson"
    image: "/images/client-3.jpg"
    designation: "Systems Analyst"
    content : "This team proved to be efficient problem solvers throughout our project. When faced with challenges, they tackled them with creativity and resourcefulness. Their ability to overcome obstacles ensured a smooth and successful project delivery."


#-------------------------------
# Blog Section
blog_settings:
  enable: true
  blog_title: Writing
  blog_description:


#-------------------------------
# Videos Settings
videos_settings:
  enable: false
  videos_title: Videos
  videos_description:


#-------------------------------
# Gallery Section
gallery_settings:
  enable: true
  gallery_title: Gallery
  gallery_description:


#-------------------------------
# Newsletter Settings
mailchimp_settings:
  enable: false
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_title: Get interesting news
  mailchimp_description: Subscribe to our newsletter and we‚Äôll send you the emails of latest posts.
  mailchimp_input_text: Your email address...
  mailchimp_button_text: Join Me # Add your button text


#-------------------------------
# Social Icons Settings
social:
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/17addisonlin"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://www.instagram.com/addison.lin8/"}
- {icon: "fa-brands fa-youtube", name: "Youtube", link: "https://youtube.com"}
- {icon: "fa-brands fa-bilibili", name: "Bilibili", link: "https://space.bilibili.com/595943554"}
- {icon: "<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24'><title>Outline-wechat SVG Icon</title><path fill='currentColor' d='M15.85 8.14c.39 0 .77.03 1.14.08C16.31 5.25 13.19 3 9.44 3c-4.25 0-7.7 2.88-7.7 6.43c0 2.05 1.15 3.86 2.94 5.04L3.67 16.5l2.76-1.19c.59.21 1.21.38 1.87.47c-.09-.39-.14-.79-.14-1.21c-.01-3.54 3.44-6.43 7.69-6.43M12 5.89a.96.96 0 1 1 0 1.92a.96.96 0 0 1 0-1.92M6.87 7.82a.96.96 0 1 1 0-1.92a.96.96 0 0 1 0 1.92'/><path fill='currentColor' d='M22.26 14.57c0-2.84-2.87-5.14-6.41-5.14s-6.41 2.3-6.41 5.14s2.87 5.14 6.41 5.14c.58 0 1.14-.08 1.67-.2L20.98 21l-1.2-2.4c1.5-.94 2.48-2.38 2.48-4.03m-8.34-.32a.96.96 0 1 1 .96-.96c.01.53-.43.96-.96.96m3.85 0a.96.96 0 1 1 0-1.92a.96.96 0 0 1 0 1.92'/></svg>", name: "WeChat", link: "https://www.wechat.com"}
- {icon: "<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24'><title>Xiaohongshu SVG Icon</title><path fill='currentColor' d='M22.405 9.879c.002.016.01.02.07.019h.725a.797.797 0 0 0 .78-.972a.794.794 0 0 0-.884-.618a.795.795 0 0 0-.692.794c0 .101-.002.666.001.777m-11.509 4.808c-.203.001-1.353.004-1.685.003a2.5 2.5 0 0 1-.766-.126a.025.025 0 0 0-.03.014L7.7 16.127a.025.025 0 0 0 .01.032c.111.06.336.124.495.124c.66.01 1.32.002 1.981 0q.017 0 .023-.015l.712-1.545a.025.025 0 0 0-.024-.036zM.477 9.91c-.071 0-.076.002-.076.01l-.01.08c-.027.397-.038.495-.234 3.06c-.012.24-.034.389-.135.607c-.026.057-.033.042.003.112c.046.092.681 1.523.787 1.74c.008.015.011.02.017.02c.008 0 .033-.026.047-.044q.219-.282.371-.606c.306-.635.44-1.325.486-1.706c.014-.11.021-.22.03-.33l.204-2.616l.022-.293c.003-.029 0-.033-.03-.034zm7.203 3.757a1.4 1.4 0 0 1-.135-.607c-.004-.084-.031-.39-.235-3.06a.4.4 0 0 0-.01-.082c-.004-.011-.052-.008-.076-.008h-1.48c-.03.001-.034.005-.03.034l.021.293q.114 1.473.233 2.946c.05.4.186 1.085.487 1.706c.103.215.223.419.37.606c.015.018.037.051.048.049c.02-.003.742-1.642.804-1.765c.036-.07.03-.055.003-.112m3.861-.913h-.872a.126.126 0 0 1-.116-.178l1.178-2.625a.025.025 0 0 0-.023-.035l-1.318-.003a.148.148 0 0 1-.135-.21l.876-1.954a.025.025 0 0 0-.023-.035h-1.56q-.017 0-.024.015l-.926 2.068c-.085.169-.314.634-.399.938a.5.5 0 0 0-.02.191a.46.46 0 0 0 .23.378a1 1 0 0 0 .46.119h.59c.041 0-.688 1.482-.834 1.972a.5.5 0 0 0-.023.172a.47.47 0 0 0 .23.398c.15.092.342.12.475.12l1.66-.001q.017 0 .023-.015l.575-1.28a.025.025 0 0 0-.024-.035m-6.93-4.937H3.1a.032.032 0 0 0-.034.033c0 1.048-.01 2.795-.01 6.829c0 .288-.269.262-.28.262h-.74c-.04.001-.044.004-.04.047c.001.037.465 1.064.555 1.263c.01.02.03.033.051.033c.157.003.767.009.938-.014c.153-.02.3-.06.438-.132c.3-.156.49-.419.595-.765c.052-.172.075-.353.075-.533q.003-3.495-.007-6.991a.03.03 0 0 0-.032-.032zm11.784 6.896q-.002-.02-.024-.022h-1.465c-.048-.001-.049-.002-.05-.049v-4.66c0-.072-.005-.07.07-.07h.863c.08 0 .075.004.075-.074V8.393c0-.082.006-.076-.08-.076h-3.5c-.064 0-.075-.006-.075.073v1.445c0 .083-.006.077.08.077h.854c.075 0 .07-.004.07.07v4.624c0 .095.008.084-.085.084c-.37 0-1.11-.002-1.304 0c-.048.001-.06.03-.06.03l-.697 1.519s-.014.025-.008.036s.013.008.058.008q2.622.003 5.243.002c.03-.001.034-.006.035-.033zm4.177-3.43q0 .021-.02.024c-.346.006-.692.004-1.037.004q-.021-.003-.022-.024q-.006-.651-.01-1.303c0-.072-.006-.071.07-.07l.733-.003c.041 0 .081.002.12.015c.093.025.16.107.165.204c.006.431.002 1.153.001 1.153m2.67.244a1.95 1.95 0 0 0-.883-.222h-.18c-.04-.001-.04-.003-.042-.04V10.21q.001-.198-.025-.394a1.8 1.8 0 0 0-.153-.53a1.53 1.53 0 0 0-.677-.71a2.2 2.2 0 0 0-1-.258c-.153-.003-.567 0-.72 0c-.07 0-.068.004-.068-.065V7.76c0-.031-.01-.041-.046-.039H17.93s-.016 0-.023.007q-.008.008-.008.023v.546c-.008.036-.057.015-.082.022h-.95c-.022.002-.028.008-.03.032v1.481c0 .09-.004.082.082.082h.913c.082 0 .072.128.072.128v1.148s.003.117-.06.117h-1.482c-.068 0-.06.082-.06.082v1.445s-.01.068.064.068h1.457c.082 0 .076-.006.076.079v3.225c0 .088-.007.081.082.081h1.43c.09 0 .082.007.082-.08v-3.27c0-.029.006-.035.033-.035l2.323-.003a.7.7 0 0 1 .28.061a.46.46 0 0 1 .274.407c.008.395.003.79.003 1.185c0 .259-.107.367-.33.367h-1.218c-.023.002-.029.008-.028.033q.276.655.57 1.303a.05.05 0 0 0 .04.026c.17.005.34.002.51.003c.15-.002.517.004.666-.01a2 2 0 0 0 .408-.075c.59-.18.975-.698.976-1.313v-1.981q.001-.191-.034-.38c0 .078-.029-.641-.724-.998'/></svg>", name: "Xiaohongshu (RedNote)", link: "https://www.xiaohongshu.com"}

# Other icons can be found at https://fontawesome.com/search?o=r&m=free


#-------------------------------
# Contact Settings
contact:
  email: addison.lin-1@ou.edu # Add your form_id
  description: Priam comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Priam theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: "G-KD9KRX7K1R"  # Add your GA Tracking Id here
